# Generated by Django 4.0.6 on 2022-07-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santamaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='imagen',
            field=models.ImageField(null=True, upload_to='proveedor'),
        ),
    ]
