# Generated by Django 4.0.6 on 2022-07-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santamaria', '0002_proveedor_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(null=True, upload_to='cliente'),
        ),
    ]
