# Generated by Django 4.0.6 on 2022-07-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santamaria', '0003_cliente_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'reserva'], [1, 'consulta'], [2, 'reclamo'], [3, 'sugerencia']])),
                ('message', models.TextField()),
                ('avisos', models.BooleanField()),
            ],
        ),
    ]
